config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  #adminのルート
  devise_for :admin
  namespace :admin do
    resources :members, only: [:index,:show,:edit,:update]
    resources :products, only: [:index,:new,:create,:edit,:update,:show]
    resources :genres,only: [:index,:create,:edit,:update,:show]
    resources :orders, only: [:index, :show, :update]
    root to: 'orders#index'
    resources :order_products, only: [:update]
  end

  devise_for :members, :controllers  => {
    :registrations => 'members/registrations',
    :sessions => 'members/sessions'
  }

  scope module: :members do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    resource :members, only: [:show,:update]
    get 'members/myedit' => 'members#edit'
    patch 'members/myedit' => 'members#update'
    patch 'members/withdraw' => 'members#withdraw', as: :members_withdraw
    get 'members/leave' => 'members#leave'
    resources :products, only: [:show, :index]
    get 'search' => 'search'
    resources :cart_products, only: [:index, :create, :update, :destroy]
    delete 'cart_products' => 'cart_products#destroy_all', as: :destroy_all_members_cart_products
    post '/orders/info'  => 'orders#info'
    get  '/orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :create, :show, :index]
    resources :destinations, only: [:index, :create, :edit, :update, :destroy]
  end

end

app/models/order.rb
class Order < ApplicationRecord
    
    enum received_status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3,"発送済み": 4}
    enum payment_method: {"クレジットカード": 0, "銀行振込": 1}
    
    belongs_to :member
    has_many :order_products, dependent: :destroy
    
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    if params[:name].present?
      member = Member.find(params[:name])
      @orders = member.orders.page(params[:page]).per(14).order("#{sort_column} #{sort_direction}")
    elsif params[:received].present?
      received = params[:received]
      @orders = Order.where(received_status: received.to_i).page(params[:page]).per(14).order("#{sort_column} #{sort_direction}")
    else
      @orders = Order.page(params[:page]).per(14).order("#{sort_column} #{sort_direction}")
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end

  def update
    @order = Order.find(params[:id])
    @order_products = @order.order_products
    @order.update(order_params)
		if @order.received_status == "入金確認"
		   @order_products.update_all(production_status:1)
		end
		   redirect_to request.referer

  end

  def sort_direction
    %w[desc asc].include?(params[:direction]) ? params[:direction] : 'desc'
  end

  def sort_column
    Order.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end

  private

    def order_params
      params.require(:order).permit(:received_status)
    end

end

app/controllers/members/orders_controller.rb
class Members::OrdersController < ApplicationController

  def new
    @member = Member.find(current_member.id)
    @destination = Destination.new
  end

  def info
    @member = Member.find(current_member.id)
    @cart_products = @member.cart_products.all
    @payment = params[:payment_method] == "0" ? 0 : 1
    if params[:destination_kind] == "0"
      @postal_code = @member.postal_code
      @address = @member.address
      @name = @member.last_name + @member.first_name
    elsif params[:destination_kind] == "1"
      @destination = Destination.find(params[:destinations])
      @postal_code = @destination.postal_code
      @address = @destination.address
      @name = @destination.name
    else
      @destination = Destination.new(destination_params)
      @destination.member_id = current_member.id
      if @destination.save
        @postal_code = @destination.postal_code
        @address = @destination.address
        @name = @destination.name
      else
        render :new
      end
    end
    @order = Order.new
  end

  def create
    order = current_member.orders.new(order_params)
    order.save
    member = Member.find(current_member.id)
    cart_products = member.cart_products.all
    cart_products.each do |cart_product|
      order_product = OrderProduct.new
      order_product.order_id = order.id
      order_product.product_id = cart_product.product_id
      order_product.subtotal_price = cart_product.quantity * ( cart_product.product.price * $tax_rate).floor
      order_product.quantity = cart_product.quantity
      order_product.save
      cart_product.destroy
    end
    #order_product = current_member.order_product.new(order_product_params)
    redirect_to orders_thanks_path
  end

  def thanks
  end

  def index
    @member = Member.find(current_member.id)
    @orders = @member.orders.all
  end

  def show
    if params[:id] == "info"
      redirect_to orders_path
    else
    @member = Member.find(current_member.id)
    @order = @member.orders.find(params[:id])
    end
  end

private

  def destination_params
    params.require(:destination).permit(:member_id,:postal_code, :address, :name)
  end

  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :potage, :total_price, :payment_method, :received_status)
  end

  # def order_product_params
  #   params.require(:order_product).permit(:subtotal_price, :quantity, :production_status)
  # end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  
  def sort_ordero(column, title)
    css_class = column == sort_columno ? "current #{sort_directiono}" : nil
    direction = column == sort_columno && sort_directiono == 'desc' ? 'asc' : 'desc'
    link_to title, {sort: column, direction: direction}.merge(), class: "sort_header #{css_class}"
  end  
  def sort_directiono
    %w[desc asc].include?(params[:direction]) ? params[:direction] : 'desc'
  end

  def sort_columno
    Order.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
end

app/helpers/members/orders_helper.rb
module Members::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class="mt-3 pb-4">注文履歴一覧</h2>
      <table class="table">
        <thead class="table-skyblue">
          <tr>
            <th width="200px"><%= sort_ordero "created_at","購入日時" %></th>
            <th><%= sort_ordero "name","購入者" %></th>
            <th class="table-mini">注文個数</th>
            <th class="table-mini"><%#= sort_ordero "received_status","注文ステータス"%>
            <%= form_with url: admin_orders_path, method: :get, local:true do |f| %>
              <%= f.select :received, Order.received_statuses, prompt: "注文ステータス"%>
              <% f.submit %>
              <% end %>
              <script>
              $('#received').on('change', function(event) {
                  $('form').submit();
                });
              </script>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td>
                <%= link_to admin_order_path(order) do %>
                  <%= l order.created_at %>
                <% end %>
              </td>
              <td>
                <%= link_to admin_member_path(order.member.id) do %>
                  <%= order.member.last_name %> <%= order.member.first_name %>
                <% end %>
              </td>
              <td align="right"><span class="mr-2"><%= order.order_products.count %></span></td>
              <td align="center"><%= order.received_status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1">
      <div class="mt-3 d-flex align-items-end">
      <h2>注文履歴詳細</h2>
      <h5 class="ml-5"><%= @order.member.last_name %><%= @order.member.first_name %>様</h5>
      </div>
      <div class= "d-flex justify-content-between">
        <div class="col-8" id="col-left0">
          <strong>注文情報</strong>
          <table class= "table" id= "table-borders">
            <thead class="table-skyblue">
              <tr>
                <th width="110px">注文日</th>
                <td><%= l @order.created_at,format: :short %></td>
              </tr>
              <tr>
                <th class="align-middle">配送先</th>
                <td>〒<%= add_ress(@order.postal_code) %><br><%= @order.address %><br><%= @order.name %></td>
              </tr>
              <tr>
                <th>支払方法</th>
                <td><%= @order.payment_method %></td>
              </tr>
              <tr>
                <th class="table-mini align-middle">注文ステータス</th>
                <td>
                  <%= form_with model:@order,url: admin_order_path, local: true do |f| %>
                      <%= f.select :received_status, Order.received_statuses.keys, class: "received_status" %>
                      <%= f.submit '更新' %>
                  <% end %>
                </td>
              </tr>
            </thead>
          </table>
        </div>
        <div>
          <strong>請求情報</strong>
          <table class= "table" id= "total-table">
            <thead class="table-skyblue" id= "table-borders">
              <tr>
                <th width= "95px">商品合計</th>
                <td>￥<%= (@order.total_price - @order.potage).to_s(:delimited, delimiter: ',') %></td>
              </tr>
              <tr>
                <th>配送料</th>
                <td>￥<%= @order.potage.to_s(:delimited, delimiter: ',') %></td>
              </tr>
              <tr>
                <th>請求金額</th>
                <td>￥<%= @order.total_price.to_s(:delimited, delimiter: ',') %></td>
              </tr>
            </thead>
          </table>
        </div>
      </div>
      <div>
        <strong>注文内容</strong>
        <table class= "table table-sm" id= "table-borders">
          <thead>
            <tr class="table-skyblue">
              <th>商品</th>
              <th width= "100px">単価(税込)</th>
              <th width= "70px">個数</th>
              <th width= "110px">小計</th>
              <th>製作ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @order.order_products.each do |order_product| %>
              <tr>
                <td><%= link_to admin_product_path(order_product.product.id) do %>
                  <%= attachment_image_tag order_product.product, :image, size:"50x50", format: 'jpeg', fallback:"no_image.jpg" %>
                  <span class= "ml-2"><%= order_product.product.name %></span>
                <% end %></td>
                <td class="align-middle">￥<%= (order_product.subtotal_price / order_product.quantity).to_s(:delimited, delimiter: ',') %></td>
                <td class="align-middle text-right"><span class="mr-2"><%= order_product.quantity.to_s(:delimited, delimiter: ',') %></td></span>
                <td class="align-middle">￥<%= order_product.subtotal_price.to_s(:delimited, delimiter: ',') %></td>
                <td class="table-mini">
                  <%= form_with model: order_product, url: admin_order_product_path(order_product.id) ,method: :patch, local: true do |f| %>
                    <%= f.select :production_status, OrderProduct.production_statuses.keys, class: "production_status" %>
                    <%= f.submit '更新' %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>