config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  #adminのルート
  devise_for :admin
  namespace :admin do
    resources :members, only: [:index,:show,:edit,:update]
    resources :products, only: [:index,:new,:create,:edit,:update,:show]
    resources :genres,only: [:index,:create,:edit,:update,:show]
    resources :orders, only: [:index, :show, :update]
    root to: 'orders#index'
    resources :order_products, only: [:update]
  end

  devise_for :members, :controllers  => {
    :registrations => 'members/registrations',
    :sessions => 'members/sessions'
  }

  scope module: :members do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    resource :members, only: [:show,:update]
    get 'members/myedit' => 'members#edit'
    patch 'members/myedit' => 'members#update'
    patch 'members/withdraw' => 'members#withdraw', as: :members_withdraw
    get 'members/leave' => 'members#leave'
    resources :products, only: [:show, :index]
    get 'search' => 'search'
    resources :cart_products, only: [:index, :create, :update, :destroy]
    delete 'cart_products' => 'cart_products#destroy_all', as: :destroy_all_members_cart_products
    post '/orders/info'  => 'orders#info'
    get  '/orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :create, :show, :index]
    resources :destinations, only: [:index, :create, :edit, :update, :destroy]
  end

end

app/models/order.rb
class Order < ApplicationRecord
    
    enum received_status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3,"発送済み": 4}
    enum payment_method: {"クレジットカード": 0, "銀行振込": 1}
    
    belongs_to :member
    has_many :order_products, dependent: :destroy
    
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
   before_action :authenticate_admin!

  def index
    if params[:word].present?
      @word = params[:word]
      @members= search(@word,Member).page(params[:page]).per(14)
    else
      @members = Member.page(params[:page]).per(14).order("#{sort_column} #{sort_direction}")
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member= Member.find(params[:id])
    if @member.update(member_params)
      flash[:notice] = "登録情報を変更しました"
      redirect_to admin_member_path(@member)
    else
      render "edit"
    end
  end
  
  def search(word, item)
    words = word.split(/[[:blank:]]+/).select(&:present?)
    not_word, or_and_word = words.partition { |word| word.start_with?("-") }
    or_word, and_word = or_and_word.partition { |word| word.start_with?("|") }
    
    items = item.all
    and_word.each do |word|
      items = items.where("last_name LIKE ? OR first_name LIKE ? OR email LIKE ?","%#{word}%","%#{word}%","#{word}")# if word.present?
    end
    or_word.each do |word|
      items = items.or(item.where("last_name LIKE ? OR first_name LIKE ?","%#{word.delete_prefix('|')}%","%#{word.delete_prefix('|')}%","%#{word.delete_prefix('|')}%"))
    end
    not_word.each do |word|
      items.where!("last_name LIKE ? OR first_name LIKE ?", "%#{word.delete_prefix('-')}%", "%#{word.delete_prefix('-')}%", "%#{word.delete_prefix('-')}%")
    end
    return items
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    Member.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
  
  private

  def member_params
  	params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number,:is_deleted)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    if params[:name].present?
      member = Member.find(params[:name])
      @orders = member.orders.page(params[:page]).per(14).order("#{sort_column} #{sort_direction}")
    elsif params[:received].present?
      received = params[:received]
      @orders = Order.where(received_status: received.to_i).page(params[:page]).per(14).order("#{sort_column} #{sort_direction}")
    else
      @orders = Order.page(params[:page]).per(14).order("#{sort_column} #{sort_direction}")
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end

  def update
    @order = Order.find(params[:id])
    @order_products = @order.order_products
    @order.update(order_params)
		if @order.received_status == "入金確認"
		   @order_products.update_all(production_status:1)
		end
		   redirect_to request.referer

  end

  def sort_direction
    %w[desc asc].include?(params[:direction]) ? params[:direction] : 'desc'
  end

  def sort_column
    Order.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end

  private

    def order_params
      params.require(:order).permit(:received_status)
    end

end

app/controllers/members/cart_products_controller.rb
class Members::CartProductsController < ApplicationController

    def index
        @member = Member.find(current_member.id)
        @cart_products = @member.cart_products.all
    end

    def update
        @cart_product = CartProduct.find(params[:id])
        if @cart_product.update(cart_product_params)
            render :index
        else
            @member = Member.find(current_member.id)
            @cart_products = @member.cart_products.all
            render :index
        end
    end

    def create
        member = Member.find(current_member.id)
        cart_product = member.cart_products.new(cart_product_params)
        if cart_product.save
            redirect_to product_path(cart_product.product_id) ,notice: "カートに#{cart_product.product.name}を追加しました。カート内に#{member.cart_products.count}商品があります。"
        else
            # $error = cart_product
            redirect_to product_path(cart_product.product_id)
            # render template: "products/show.html.erb"
        end
    end

    def destroy
        @cart_product = CartProduct.find(params[:id])
        @cart_product.destroy
        redirect_to cart_products_path
    end

    def destroy_all
        @member = Member.find(current_member.id)
        @cart_products = @member.cart_products.all
        @cart_products.each do |cart_product|
            cart_product.destroy
        end
        redirect_to products_path
    end

private

    def cart_product_params
        params.require(:cart_product).permit(:quantity, :product_id)
    end
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/destinations_controller.rb
class Members::DestinationsController < ApplicationController


  def create
   @destination = Destination.new(destination_params)
   @destination.member_id = current_member.id
    if @destination.save
      redirect_to destinations_path
    else
      @member = current_member
      render "index"
    end
  end

  def index
    @member = current_member
    @destination = Destination.new
  end

  def edit
    @destination = Destination.find(params[:id])
  end

  def update
    @destination = Destination.find(params[:id])
    if @destination.update(destination_params)
      redirect_to destinations_path
    else
      render :edit
    end
  end

  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy
    redirect_to destinations_path
  end

  private

  def destination_params
    params.require(:destination).permit(:member_id,:postal_code, :address, :name)
  end


end

app/controllers/members/homes_controller.rb
class Members::HomesController < ApplicationController

  def top
    @products = Product.limit(4).order("created_at DESC") #asc 昇順 desc 降順
    @genres = Genre.all
    render 'top',layout: false
  end

  def about
  end


end

app/controllers/members/members_controller.rb
class Members::MembersController < ApplicationController
   before_action :authenticate_member!

  def show
    @member = Member.find(current_member.id)
  end

  def edit
    @member = Member.find(current_member.id)
  end

  def update
    @member= Member.find(current_member.id)
    if @member.update(member_params)
      flash[:notice] = "登録情報を保存しました"
      redirect_to members_path(current_member.id)
    else
      render :edit
    end
  end

  def leave
    @member=Member.find(current_member.id)
  end

  def withdraw
    @member = Member.find(current_member.id)
    @member.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def member_params
  	params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number,:is_deleted)
  end


end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/orders_controller.rb
class Members::OrdersController < ApplicationController

  def new
    @member = Member.find(current_member.id)
    @destination = Destination.new
  end

  def info
    @member = Member.find(current_member.id)
    @cart_products = @member.cart_products.all
    @payment = params[:payment_method] == "0" ? 0 : 1
    if params[:destination_kind] == "0"
      @postal_code = @member.postal_code
      @address = @member.address
      @name = @member.last_name + @member.first_name
    elsif params[:destination_kind] == "1"
      @destination = Destination.find(params[:destinations])
      @postal_code = @destination.postal_code
      @address = @destination.address
      @name = @destination.name
    else
      @destination = Destination.new(destination_params)
      @destination.member_id = current_member.id
      if @destination.save
        @postal_code = @destination.postal_code
        @address = @destination.address
        @name = @destination.name
      else
        render :new
      end
    end
    @order = Order.new
  end

  def create
    order = current_member.orders.new(order_params)
    order.save
    member = Member.find(current_member.id)
    cart_products = member.cart_products.all
    cart_products.each do |cart_product|
      order_product = OrderProduct.new
      order_product.order_id = order.id
      order_product.product_id = cart_product.product_id
      order_product.subtotal_price = cart_product.quantity * ( cart_product.product.price * $tax_rate).floor
      order_product.quantity = cart_product.quantity
      order_product.save
      cart_product.destroy
    end
    #order_product = current_member.order_product.new(order_product_params)
    redirect_to orders_thanks_path
  end

  def thanks
  end

  def index
    @member = Member.find(current_member.id)
    @orders = @member.orders.all
  end

  def show
    if params[:id] == "info"
      redirect_to orders_path
    else
    @member = Member.find(current_member.id)
    @order = @member.orders.find(params[:id])
    end
  end

private

  def destination_params
    params.require(:destination).permit(:member_id,:postal_code, :address, :name)
  end

  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :potage, :total_price, :payment_method, :received_status)
  end

  # def order_product_params
  #   params.require(:order_product).permit(:subtotal_price, :quantity, :production_status)
  # end

end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/products_controller.rb
class Members::ProductsController < ApplicationController

  def index
    if params[:word].present?
      @product_name = "商品：" + params[:word]
      @word = params[:word]
      @products = search(@word , Product).page(params[:page]).per(6)
      if @products.blank?
        @products = "no_search"
      end
    elsif params[:genre].present?
      @gunre_name = "ジャンル：" + params[:genre]
      @gunre = Genre.search(params[:genre])
      @products =  @gunre[0].products.page(params[:page]).per(6)
      if @products.blank?
        @products = "no_search"
      end
    else
      @products = Product.page(params[:page]).order(id: "DESC").per(6)
    end
    @genres = Genre.all
  end

  def show
    @product = Product.find(params[:id])
    @cart_product = CartProduct.new
    @genres = Genre.all
  end


  def search(word, item)
    words = word.split(/[[:blank:]]+/).select(&:present?)
    not_word, or_and_word = words.partition { |word| word.start_with?("-") }
    or_word, and_word = or_and_word.partition { |word| word.start_with?("|") }

    items = item.all
    and_word.each do |word|
      items = items.where("name LIKE ?","%#{word}%")# if word.present?
    end
    or_word.each do |word|
      items = items.or(item.where("name LIKE ?","%#{word.delete_prefix('|')}%"))
    end
    not_word.each do |word|
      items.where!("name NOT LIKE ?", "%#{word.delete_prefix('-')}%")
    end
    return items
  end


   private
     def product_params
       params.require(:product).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
     end


end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  #会員サインアップ時
  def after_sign_up_path_for(resource)
      members_path
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
  
  def sort_orderm(column, title)
    css_class = column == sort_columnm ? "current #{sort_directionm}" : nil
    direction = column == sort_columnm && sort_directionm == 'desc' ? 'asc' : 'desc'
    link_to title, {sort: column, direction: direction}.merge(), class: "sort_header #{css_class}"
  end  
  def sort_directionm
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_columnm
    Member.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
  
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  
  def sort_ordero(column, title)
    css_class = column == sort_columno ? "current #{sort_directiono}" : nil
    direction = column == sort_columno && sort_directiono == 'desc' ? 'asc' : 'desc'
    link_to title, {sort: column, direction: direction}.merge(), class: "sort_header #{css_class}"
  end  
  def sort_directiono
    %w[desc asc].include?(params[:direction]) ? params[:direction] : 'desc'
  end

  def sort_columno
    Order.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
end

app/helpers/members/cart_products_helper.rb
module Members::CartProductsHelper
end

app/helpers/members/destinations_helper.rb
module Members::DestinationsHelper
end

app/views/members/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1">
      <% if @orders.any? %>
        <p class="page-title">orders history</p>
        <table class= "table" id= "table-borders">
          <thead>
            <tr class="table-skyblue">
              <th>注文日</th>
              <th width= "40%">配送先</th>
              <th>注文商品</th>
              <th>支払金額</th>
              <th class="table-mini">ステータス</th>
              <th class="table-mini">注文詳細</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td><%= l order.created_at,format: :short %></td>
                <td>〒<%= add_ress(order.postal_code) %><br><%= order.address %><br><%= order.name %></td>
                <td class="table-mini">
                  <% order.order_products.each do |order_product| %>
                    <div><%= order_product.product.name %></div>
                  <% end %>
                </td>
                <td>￥<%= order.total_price.to_s(:delimited, delimiter: ',') %></td>
                <td><%= order.received_status %></td>
                <td><%= link_to "表示する", order_path(order.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <h2 class= "mt-3">注文履歴はありません</h2>
      <% end %>
    </div>
  </div>
</div>

app/views/members/orders/info.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1">
      <p class="page-title">order confirmation</p>
      <table class= "table table-sm mt-3" id= "table-borders">
        <thead>
          <tr class="table-skyblue">
            <th>商品名</th>
            <th width= "100px">単価(税込)</th>
            <th width= "100px">数量</th>
            <th width= "110px">小計</th>
          </tr>
        </thead>
        <tbody>
          <% @total = 0 %>
          <% @cart_products.each do |cart_product| %>
          <tr>
            <td>
              <%= attachment_image_tag cart_product.product, :image, size:"50x50", format: 'jpeg', fallback:"no_image.jpg" %>
              <span class= "ml-2"><%= cart_product.product.name %></span>
            </td>
            <!--税込価格は切捨て-->
            <td class="align-middle">￥<%= (cart_product.product.price * $tax_rate).floor.to_s(:delimited, delimiter: ',') %></td>
            <!--数量-->
            <td class="align-middle"><%= (cart_product.quantity).to_s(:delimited, delimiter: ',') %></td>
            <!--小計の表示:数量ｘ(価格ｘ税率)-->
            <td class="align-middle">￥<%= (cart_product.quantity * (cart_product.product.price * $tax_rate).floor).to_s(:delimited, delimiter: ',') %></td>
            <!--@totalに数量ｘ(価格ｘ税率)を代入-->
          </tr><% (@total += cart_product.quantity * (cart_product.product.price * $tax_rate).floor).to_s(:delimited, delimiter: ',') %>
          <% end %>
        </tbody>
      </table>

      <%= form_with model: @order, local: :true do |f| %>
        <%= f.hidden_field :postal_code , value: @postal_code %>
        <%= f.hidden_field :address , value: @address %>
        <%= f.hidden_field :name , value: @name %>
        <%= f.hidden_field :potage , value: $potage %>
        <%= f.hidden_field :total_price , value: @total + $potage %>
        <%= f.hidden_field :payment_method , value: Order.payment_methods.keys[@payment] %>
        <div class= "d-flex justify-content-between mt-3">
          <div>
            <div><strong>支払方法 ：<%= Order.payment_methods.keys.to_a[@payment] %></strong></div>
            <div class="mt-2" ><strong>お届け先
            <div class="ml-4 mt-1" >
              <div class="mt-1">〒<%= add_ress(@postal_code) %></div>
              <div class="mt-1"><%= @address %></div>
              <div class="mt-1"><%= @name %></div>
            </div>
            </strong></div>
          </div>
          <table class= "table ml-auto" id="total-table">
            <thead class="table-skyblue" id= "table-borders">
              <tr>
                <th width= "100px">送料</th>
                <td>￥<%= $potage.to_s(:delimited, delimiter: ',') %></td>
              </tr>
              <tr>
                <th>商品合計</th>
                <td>￥<%= @total.to_s(:delimited, delimiter: ',') %></td>
              </tr>
              <tr>
                <th>請求金額</th>
                <td>￥<%= (@total + $potage).to_s(:delimited, delimiter: ',') %></td>
              </tr>
            </thead>
          </table>
        </div>
        <% if @cart_products.any? %>
          <%= f.submit "注文を確定する" ,class:"btn btn-success" %>
        <% else %>
          <%= link_to "カートが空です！", cart_products_path, class:"btn btn-danger" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/members/orders/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1">
      <p class="page-title">order input</p>
      <%= render "members/shared/error_messages", resource: @destination %>
      <p><strong>支払方法</strong></p>
      <%= form_with url: orders_info_path, local: :true do |f| %>
        <div class= "ml-4 mt-2">
          <%= f.radio_button :payment_method ,0 ,checked: true %>
          <%= f.label :payment_method,  Order.payment_methods.keys.to_a[0] %>
        </div>
        <div class= "ml-4">
          <%= f.radio_button :payment_method ,1 %>
          <%= f.label :payment_method,  Order.payment_methods.keys.to_a[1] %>
        </div>
        <strong>お届け先</strong>
        <div class= "ml-4 mt-2">
          <%= f.radio_button :destination_kind ,0 ,checked: true %>
          <%= f.label :destination_kind,  "ご自身の住所" %>
          <div class= "ml-4">〒<%= add_ress(@member.postal_code) %><br><%= @member.address %><br><%= @member.last_name %> <%= @member.first_name %></div>
        </div>
        <% if @member.destinations.any? %>
          <div class= "ml-4">
            <%= f.radio_button :destination_kind ,1 %>
            <%= f.label :destination_kind,  "登録住所から選択" %>
            <div class= "ml-4"><%= f.collection_select :destinations, @member.destinations, :id ,:destinations_address, class: "col-10" %></div>
          </div>
        <% end %>
        <div class= "ml-4 mt-2">
            <%= f.radio_button :destination_kind ,2 %>
            <%= f.label "新しいお届け先" %>
          <div class= "ml-4">
            <%= form_with model: @destination, url: orders_info_path, method: :post, local: :true do |f| %>
              <div class="mt-2 row">
                <%= f.label "郵便番号(ハイフン無し)", class:"col-3 col-form-label" %>
                <div class="col-3"><%= f.text_field :postal_code, placeholder: "1234567", maxlength: 7,minlength: 7, class:"form-control form-control-sm",id: "form-border" %></div>
              </div>
              <div class="mt-2 row">
                <%= f.label "住所", class:"col-3 col-form-label" %>
                <div class="col-8"><%= f.text_field :address, placeholder: "東京都渋谷区代々木神園0-0", class:"form-control form-control-sm",id: "form-border" %></div>
              </div>
              <div class="mt-2 row">
                <%= f.label "宛名", class:"col-3 col-form-label" %>
                <div class="col-4"><%= f.text_field :name, placeholder: "長野恵子", class:"form-control form-control-sm",id: "form-border" %></div>
              </div>
            <% end %>
          </div>
        <%= f.submit "確認画面へ進む", class: "mt-2 btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/members/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1">
      <p class="page-title">order history details</p>
      <div class= "d-flex justify-content-between">
        <div class="col-8" id="col-left0">
          <strong>注文情報</strong>
          <table class= "table" id= "table-borders">
            <thead class="table-skyblue">
              <tr>
                <th width="110px">注文日</th>
                <td><%= l @order.created_at,format: :short %></td>
              </tr>
              <tr>
                <th class="align-middle">配送先</th>
                <td>〒<%= add_ress(@order.postal_code) %><br><%= @order.address %><br><%= @order.name %></td>
              </tr>
              <tr>
                <th>支払方法</th>
                <td><%= @order.payment_method %></td>
              </tr>
              <tr>
                <th>ステータス</th>
                <td><%= @order.received_status %></td>
              </tr>
            </thead>
          </table>
        </div>
        <div>
          <strong>請求情報</strong>
          <table class= "table" id= "total-table">
            <thead class="table-skyblue" id= "table-borders">
              <tr>
                <th width= "95px">商品合計</th>
                <td>￥<%= (@order.total_price - @order.potage).to_s(:delimited, delimiter: ',') %></td>
              </tr>
              <tr>
                <th>配送料</th>
                <td>￥<%= @order.potage.to_s(:delimited, delimiter: ',') %></td>
              </tr>
              <tr>
                <th>請求金額</th>
                <td>￥<%= @order.total_price.to_s(:delimited, delimiter: ',') %></td>
              </tr>
            </thead>
          </table>
        </div>
      </div>
      <div>
        <strong>注文内容</strong>
        <table class= "table table-sm" id= "table-borders">
          <thead>
            <tr class="table-skyblue">
              <th>商品</th>
              <th width= "100px">単価(税込)</th>
              <th width= "100px">個数</th>
              <th width= "110px">小計</th>
            </tr>
          </thead>
          <tbody>
            <% @order.order_products.each do |order_product| %>
              <tr>
                <td><%= link_to product_path(order_product.product.id) do %>
                  <%= attachment_image_tag order_product.product, :image, size:"50x50", format: 'jpeg', fallback:"no_image.jpg" %>
                  <span class= "ml-2"><%= order_product.product.name %></span>
                <% end %></td>
                <td class="align-middle">￥<%= (order_product.subtotal_price / order_product.quantity).to_s(:delimited, delimiter: ',') %></td>
                <td class="align-middle"><%= order_product.quantity.to_s(:delimited, delimiter: ',') %></td>
                <td class="align-middle">￥<%= order_product.subtotal_price.to_s(:delimited, delimiter: ',') %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/members/orders/thanks.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1">
      <div class= "mt-5 pt-5 text-center">
        <p class="page-title">Thank you for your order！</p>
        <p class="page-title">Expected to arrive in 7days. </p>
      </div>
      <div class= "mt-5 text-right ">
        <%= link_to "買い物を続ける", products_path, class:"btn btn-primary" %>
        <%= link_to "注文履歴", orders_path, class:"btn btn-success" %>
        </div>
    </div>
  </div>
</div>