config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  #adminのルート
  devise_for :admin
  namespace :admin do
    resources :members, only: [:index,:show,:edit,:update]
    resources :products, only: [:index,:new,:create,:edit,:update,:show]
    resources :genres,only: [:index,:create,:edit,:update,:show]
    resources :orders, only: [:index, :show, :update]
    root to: 'orders#index'
    resources :order_products, only: [:update]
  end

  devise_for :members, :controllers  => {
    :registrations => 'members/registrations',
    :sessions => 'members/sessions'
  }

  scope module: :members do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    resource :members, only: [:show,:update]
    get 'members/myedit' => 'members#edit'
    patch 'members/myedit' => 'members#update'
    patch 'members/withdraw' => 'members#withdraw', as: :members_withdraw
    get 'members/leave' => 'members#leave'
    resources :products, only: [:show, :index]
    get 'search' => 'search'
    resources :cart_products, only: [:index, :create, :update, :destroy]
    delete 'cart_products' => 'cart_products#destroy_all', as: :destroy_all_members_cart_products
    post '/orders/info'  => 'orders#info'
    get  '/orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :create, :show, :index]
    resources :destinations, only: [:index, :create, :edit, :update, :destroy]
  end

end

app/models/product.rb
class Product < ApplicationRecord

    has_many :cart_products
    has_many :order_products
    belongs_to :genre

    attachment :image
    validates :name, presence:true
    validates :introduction, presence:true
    validates :price, presence:true

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_admin!

  def new
    @product = Product.new
  end

  def index
    if params[:word].present?
      @word = params[:word]
      @products = search(@word , Product).page(params[:page]).per(14)
    else
      @products = Product.page(params[:page]).per(14).order("#{sort_column} #{sort_direction}")
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product), notice: "商品を登録しました。"
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(params[:id]), notice:"商品情報を更新しました。"
    else
      render :edit
    end
  end

  def search(word, item)
    words = word.split(/[[:blank:]]+/).select(&:present?)
    not_word, or_and_word = words.partition { |word| word.start_with?("-") }
    or_word, and_word = or_and_word.partition { |word| word.start_with?("|") }
    
    items = item.all
    and_word.each do |word|
      items = items.where("name LIKE ?","%#{word}%")# if word.present?
    end
    or_word.each do |word|
      items = items.or(item.where("name LIKE ?","%#{word.delete_prefix('|')}%"))
    end
    not_word.each do |word|
      items.where!("name NOT LIKE ?", "%#{word.delete_prefix('-')}%")
    end
    return items
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
  
  
private

    def product_params
      params.require(:product).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
    end

end

app/controllers/members/products_controller.rb
class Members::ProductsController < ApplicationController

  def index
    if params[:word].present?
      @product_name = "商品：" + params[:word]
      @word = params[:word]
      @products = search(@word , Product).page(params[:page]).per(6)
      if @products.blank?
        @products = "no_search"
      end
    elsif params[:genre].present?
      @gunre_name = "ジャンル：" + params[:genre]
      @gunre = Genre.search(params[:genre])
      @products =  @gunre[0].products.page(params[:page]).per(6)
      if @products.blank?
        @products = "no_search"
      end
    else
      @products = Product.page(params[:page]).order(id: "DESC").per(6)
    end
    @genres = Genre.all
  end

  def show
    @product = Product.find(params[:id])
    @cart_product = CartProduct.new
    @genres = Genre.all
  end


  def search(word, item)
    words = word.split(/[[:blank:]]+/).select(&:present?)
    not_word, or_and_word = words.partition { |word| word.start_with?("-") }
    or_word, and_word = or_and_word.partition { |word| word.start_with?("|") }

    items = item.all
    and_word.each do |word|
      items = items.where("name LIKE ?","%#{word}%")# if word.present?
    end
    or_word.each do |word|
      items = items.or(item.where("name LIKE ?","%#{word.delete_prefix('|')}%"))
    end
    not_word.each do |word|
      items.where!("name NOT LIKE ?", "%#{word.delete_prefix('-')}%")
    end
    return items
  end


   private
     def product_params
       params.require(:product).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
     end


end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  
  def sort_orderp(column, title)
    css_class = column == sort_columnp ? "current #{sort_directionp}" : nil
    direction = column == sort_columnp && sort_directionp == 'desc' ? 'asc' : 'desc'
    link_to title, {sort: column, direction: direction}.merge(), class: "sort_header #{css_class}"
  end  
  def sort_directionp
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_columnp
    Product.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
end

app/helpers/members/products_helper.rb
module Members::ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class="mt-3 pb-3">商品編集</h2>
      <%= render "admin/shared/error_messages", resource: @product %>
      <%= form_with model: @product, url:admin_product_path(@product), method: :patch, local:true do |f| %>
        <%#= f.hidden_field :product_id, value: @product.id %>
      <table class="table table-borderless mt-5 ">
        <tbody>
          <tr>
            <td><%= f.label :商品画像 %></td>
            <td><%= f.attachment_field :image, size:"200x200" %></td>
          </tr>
          <tr>
            <td><%= f.label :商品名 %></td>
            <td><%= f.text_field :name, size:"50", required: true %></td>
          </tr>
          <tr>
            <td><%= f.label :商品説明 %></td>
            <td><%= f.text_area :introduction, size:"53", required: true %></td>
          </tr>
          <tr>
            <td><%= f.label :ジャンル %></td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name ,prompt: '--選択してください--' %></td>
          </tr>
          <tr>
            <td><%= f.label :税抜価格 %></td>
            <td><%= f.number_field :price, required: true %></td>
          </tr>
          <tr>
            <td><%= f.label :販売ステータス %></td>
            <td>
              <div class="sale_status_form">
                <%= f.radio_button :is_active, true %>
                <%= f.label :done, '販売中', value: true %>
                <%= f.radio_button :is_active, false, class:"ml-3" %>
                <%= f.label :done, '販売停止中', value: false %>
              </div>
            </td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit "変更内容を保存", class: "btn btn-primary"  %></td>
          </tr>
      </tbody>
    </table>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 offset-1">
      <div class="d-flex justify-content-between">
        <h2 class="mt-3 pb-4">商品一覧</h2>
        <h4 class="mt-4">
          <%= link_to "新規登録", new_admin_product_path %>
            <!--<i class= "fas fa-plus-circle"></i>-->
        </h4>
      </div>
      <table class='table table-hover table-inverse'>
        <thead class="table-skyblue">
          <tr>
            <th class="table-mini"><%= sort_orderp "created_at", "商品ID" %></th>
            <th width="50%"><%= sort_orderp "name" ,"商品名" %></th>
            <th><%= sort_orderp "price","税抜き価格" %></th>
            <th><%= sort_orderp "genre_id","ジャンル" %></th>
            <th class="table-mini"><%= sort_orderp "is_active","ステータス" %></th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td>
                <%= product.id %>
              </td>
              <td>
                <%= link_to admin_product_path(product) do %>
                <%= product.name %>
                <% end %>
              </td>
              <td>
                  ￥<%= product.price.to_s(:delimited, delimiter: ',') %>
              </td>
              <td>
                  <%= product.genre.name %>
              </td>
              <td align="center">
                  <% if product.is_active == true %>
                  <span class="status-true">販売中</span>
                  <% else %>
                  <span class="status-false">販売停止中</span>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @products %>
   </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class="mt-3 pb-3">新商品登録</h2>
      <%= render "admin/shared/error_messages", resource: @product %>
      <%= form_with model: @product,url:admin_products_path, local:true do |f| %>
         <%#= f.hidden_field :product_id, value: @product.id %>
      <table class="table table-borderless mt-5 ">
        <tbody>
          <tr>
            <td><%= f.label :商品画像 %></td>
            <td><%= f.attachment_field :image, size:"200x200" %></td>
          </tr>
          <tr>
            <td><%= f.label :商品名 %></td>
            <td><%= f.text_field :name, size:"50", required: true %></td>
          </tr>
          <tr>
            <td><%= f.label :商品説明 %></td>
            <td><%= f.text_area :introduction, size:"53", required: true %></td>
          </tr>
          <tr>
            <td><%= f.label :ジャンル %></td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name ,prompt: '--選択してください--' %></td>
          </tr>
          <tr>
            <td><%= f.label :税抜価格 %></td>
            <td><%= f.number_field :price, required: true %></td>
          </tr>
          <tr>
            <td><%= f.label :販売ステータス %></td>
            <td>
              <div class="sale_status_form">
                <%= f.radio_button :is_active, true %>
                <%= f.label :done, '販売中', value: true %>
                <%= f.radio_button :is_active, false, class:"ml-3" %>
                <%= f.label :done, '販売停止中', value: false %>
              </div>
            </td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit "商品の登録", class: "btn btn-primary"  %></td>
          </tr>
      </tbody>
    </table>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class="mt-3 pb-3">商品詳細</h2>

      <table class="mt-5 table table-borderless">
        <tbody>
          <tr>
            <th rowspan="6" width="250px" class="align-middle">
              <%= attachment_image_tag @product, :image, size:"200x200", format: 'jpeg', fallback:"no_image.jpg", class: "enn" %>
            </th>
            <th>商品名</th>
            <td><%= @product.name %></td>
          </tr>
          <tr>
            <th>商品説明</th>
            <td class= "text-break"><%= @product.introduction %></td>
          </tr>
          <tr>
            <th>ジャンル</th>
            <td><%= @product.genre.name %></td>
          </tr>
          <tr>
            <th>税込価格<br>税抜価格</th>
            <td><%= (@product.price*$tax_rate).floor.to_s(:delimited, delimiter: ',') %>円<br><%= @product.price.to_s(:delimited, delimiter: ',') %>円</td>
          </tr>
          <tr>
            <th class="table-mini">販売ステータス</th>
            <td>
              <% if @product.is_active == true %>
                <span class="status-true">販売中</span>
              <% else %>
                <span class="status-false">販売停止中</span>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="text-right"><%= link_to "編集する", edit_admin_product_path(@product), class:"btn btn-primary" %></div>
    </div>
  </div>
</div>