config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  #adminのルート
  devise_for :admin
  namespace :admin do
    resources :members, only: [:index,:show,:edit,:update]
    resources :products, only: [:index,:new,:create,:edit,:update,:show]
    resources :genres,only: [:index,:create,:edit,:update,:show]
    resources :orders, only: [:index, :show, :update]
    root to: 'orders#index'
    resources :order_products, only: [:update]
  end

  devise_for :members, :controllers  => {
    :registrations => 'members/registrations',
    :sessions => 'members/sessions'
  }

  scope module: :members do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    resource :members, only: [:show,:update]
    get 'members/myedit' => 'members#edit'
    patch 'members/myedit' => 'members#update'
    patch 'members/withdraw' => 'members#withdraw', as: :members_withdraw
    get 'members/leave' => 'members#leave'
    resources :products, only: [:show, :index]
    get 'search' => 'search'
    resources :cart_products, only: [:index, :create, :update, :destroy]
    delete 'cart_products' => 'cart_products#destroy_all', as: :destroy_all_members_cart_products
    post '/orders/info'  => 'orders#info'
    get  '/orders/thanks' => 'orders#thanks'
    resources :orders, only:[:new, :create, :show, :index]
    resources :destinations, only: [:index, :create, :edit, :update, :destroy]
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
   before_action :authenticate_admin!

  def index
    if params[:word].present?
      @word = params[:word]
      @members= search(@word,Member).page(params[:page]).per(14)
    else
      @members = Member.page(params[:page]).per(14).order("#{sort_column} #{sort_direction}")
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member= Member.find(params[:id])
    if @member.update(member_params)
      flash[:notice] = "登録情報を変更しました"
      redirect_to admin_member_path(@member)
    else
      render "edit"
    end
  end
  
  def search(word, item)
    words = word.split(/[[:blank:]]+/).select(&:present?)
    not_word, or_and_word = words.partition { |word| word.start_with?("-") }
    or_word, and_word = or_and_word.partition { |word| word.start_with?("|") }
    
    items = item.all
    and_word.each do |word|
      items = items.where("last_name LIKE ? OR first_name LIKE ? OR email LIKE ?","%#{word}%","%#{word}%","#{word}")# if word.present?
    end
    or_word.each do |word|
      items = items.or(item.where("last_name LIKE ? OR first_name LIKE ?","%#{word.delete_prefix('|')}%","%#{word.delete_prefix('|')}%","%#{word.delete_prefix('|')}%"))
    end
    not_word.each do |word|
      items.where!("last_name LIKE ? OR first_name LIKE ?", "%#{word.delete_prefix('-')}%", "%#{word.delete_prefix('-')}%", "%#{word.delete_prefix('-')}%")
    end
    return items
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    Member.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
  
  private

  def member_params
  	params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number,:is_deleted)
  end

end

app/controllers/members/cart_products_controller.rb
class Members::CartProductsController < ApplicationController

    def index
        @member = Member.find(current_member.id)
        @cart_products = @member.cart_products.all
    end

    def update
        @cart_product = CartProduct.find(params[:id])
        if @cart_product.update(cart_product_params)
            render :index
        else
            @member = Member.find(current_member.id)
            @cart_products = @member.cart_products.all
            render :index
        end
    end

    def create
        member = Member.find(current_member.id)
        cart_product = member.cart_products.new(cart_product_params)
        if cart_product.save
            redirect_to product_path(cart_product.product_id) ,notice: "カートに#{cart_product.product.name}を追加しました。カート内に#{member.cart_products.count}商品があります。"
        else
            # $error = cart_product
            redirect_to product_path(cart_product.product_id)
            # render template: "products/show.html.erb"
        end
    end

    def destroy
        @cart_product = CartProduct.find(params[:id])
        @cart_product.destroy
        redirect_to cart_products_path
    end

    def destroy_all
        @member = Member.find(current_member.id)
        @cart_products = @member.cart_products.all
        @cart_products.each do |cart_product|
            cart_product.destroy
        end
        redirect_to products_path
    end

private

    def cart_product_params
        params.require(:cart_product).permit(:quantity, :product_id)
    end
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/destinations_controller.rb
class Members::DestinationsController < ApplicationController


  def create
   @destination = Destination.new(destination_params)
   @destination.member_id = current_member.id
    if @destination.save
      redirect_to destinations_path
    else
      @member = current_member
      render "index"
    end
  end

  def index
    @member = current_member
    @destination = Destination.new
  end

  def edit
    @destination = Destination.find(params[:id])
  end

  def update
    @destination = Destination.find(params[:id])
    if @destination.update(destination_params)
      redirect_to destinations_path
    else
      render :edit
    end
  end

  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy
    redirect_to destinations_path
  end

  private

  def destination_params
    params.require(:destination).permit(:member_id,:postal_code, :address, :name)
  end


end

app/controllers/members/homes_controller.rb
class Members::HomesController < ApplicationController

  def top
    @products = Product.limit(4).order("created_at DESC") #asc 昇順 desc 降順
    @genres = Genre.all
    render 'top',layout: false
  end

  def about
  end


end

app/controllers/members/members_controller.rb
class Members::MembersController < ApplicationController
   before_action :authenticate_member!

  def show
    @member = Member.find(current_member.id)
  end

  def edit
    @member = Member.find(current_member.id)
  end

  def update
    @member= Member.find(current_member.id)
    if @member.update(member_params)
      flash[:notice] = "登録情報を保存しました"
      redirect_to members_path(current_member.id)
    else
      render :edit
    end
  end

  def leave
    @member=Member.find(current_member.id)
  end

  def withdraw
    @member = Member.find(current_member.id)
    @member.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def member_params
  	params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number,:is_deleted)
  end


end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/orders_controller.rb
class Members::OrdersController < ApplicationController

  def new
    @member = Member.find(current_member.id)
    @destination = Destination.new
  end

  def info
    @member = Member.find(current_member.id)
    @cart_products = @member.cart_products.all
    @payment = params[:payment_method] == "0" ? 0 : 1
    if params[:destination_kind] == "0"
      @postal_code = @member.postal_code
      @address = @member.address
      @name = @member.last_name + @member.first_name
    elsif params[:destination_kind] == "1"
      @destination = Destination.find(params[:destinations])
      @postal_code = @destination.postal_code
      @address = @destination.address
      @name = @destination.name
    else
      @destination = Destination.new(destination_params)
      @destination.member_id = current_member.id
      if @destination.save
        @postal_code = @destination.postal_code
        @address = @destination.address
        @name = @destination.name
      else
        render :new
      end
    end
    @order = Order.new
  end

  def create
    order = current_member.orders.new(order_params)
    order.save
    member = Member.find(current_member.id)
    cart_products = member.cart_products.all
    cart_products.each do |cart_product|
      order_product = OrderProduct.new
      order_product.order_id = order.id
      order_product.product_id = cart_product.product_id
      order_product.subtotal_price = cart_product.quantity * ( cart_product.product.price * $tax_rate).floor
      order_product.quantity = cart_product.quantity
      order_product.save
      cart_product.destroy
    end
    #order_product = current_member.order_product.new(order_product_params)
    redirect_to orders_thanks_path
  end

  def thanks
  end

  def index
    @member = Member.find(current_member.id)
    @orders = @member.orders.all
  end

  def show
    if params[:id] == "info"
      redirect_to orders_path
    else
    @member = Member.find(current_member.id)
    @order = @member.orders.find(params[:id])
    end
  end

private

  def destination_params
    params.require(:destination).permit(:member_id,:postal_code, :address, :name)
  end

  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :potage, :total_price, :payment_method, :received_status)
  end

  # def order_product_params
  #   params.require(:order_product).permit(:subtotal_price, :quantity, :production_status)
  # end

end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/products_controller.rb
class Members::ProductsController < ApplicationController

  def index
    if params[:word].present?
      @product_name = "商品：" + params[:word]
      @word = params[:word]
      @products = search(@word , Product).page(params[:page]).per(6)
      if @products.blank?
        @products = "no_search"
      end
    elsif params[:genre].present?
      @gunre_name = "ジャンル：" + params[:genre]
      @gunre = Genre.search(params[:genre])
      @products =  @gunre[0].products.page(params[:page]).per(6)
      if @products.blank?
        @products = "no_search"
      end
    else
      @products = Product.page(params[:page]).order(id: "DESC").per(6)
    end
    @genres = Genre.all
  end

  def show
    @product = Product.find(params[:id])
    @cart_product = CartProduct.new
    @genres = Genre.all
  end


  def search(word, item)
    words = word.split(/[[:blank:]]+/).select(&:present?)
    not_word, or_and_word = words.partition { |word| word.start_with?("-") }
    or_word, and_word = or_and_word.partition { |word| word.start_with?("|") }

    items = item.all
    and_word.each do |word|
      items = items.where("name LIKE ?","%#{word}%")# if word.present?
    end
    or_word.each do |word|
      items = items.or(item.where("name LIKE ?","%#{word.delete_prefix('|')}%"))
    end
    not_word.each do |word|
      items.where!("name NOT LIKE ?", "%#{word.delete_prefix('-')}%")
    end
    return items
  end


   private
     def product_params
       params.require(:product).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
     end


end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  #会員サインアップ時
  def after_sign_up_path_for(resource)
      members_path
  end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  #会員ログイン時
  def after_sign_in_path_for(resource)
    products_path
  end

end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
  
  def sort_orderm(column, title)
    css_class = column == sort_columnm ? "current #{sort_directionm}" : nil
    direction = column == sort_columnm && sort_directionm == 'desc' ? 'asc' : 'desc'
    link_to title, {sort: column, direction: direction}.merge(), class: "sort_header #{css_class}"
  end  
  def sort_directionm
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_columnm
    Member.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
  
end

app/helpers/members/cart_products_helper.rb
module Members::CartProductsHelper
end

app/helpers/members/destinations_helper.rb
module Members::DestinationsHelper
end

app/helpers/members/homes_helper.rb
module Members::HomesHelper
end

app/helpers/members/members_helper.rb
module Members::MembersHelper
end

app/helpers/members/orders_helper.rb
module Members::OrdersHelper
end

app/views/members/homes/about.html.erb
<body class="home">
  <div id="container">
    <header>
      <h1 class="space"></h1>
      <h1 id="logo"><strong class="page-title">NaganoCake</strong></h1>
    </header>
  <!--開閉メニュー-->
    <div id="contents">
      <section>
        <h2>人気商品<br><span>販売中</span></h2>
        <div class="list">
          <figure><%= image_tag 'sale2.jpg', class:"fuwafuwa2" %></figure>
        </div>
        <div class="list">
          <figure><%= image_tag 'sale1.jpg', class:"fuwafuwa2" %></figure>
        </div>
        <div class="list">
          <figure><%= image_tag 'sale4.jpg', class:"fuwafuwa2" %></figure>
        </div>
      </section>
      <section id="new">
        <h2>News<br><span>お知らせ</span></h2>
        <dl>
          <dt>2021/08/04</dt>
          <dd>チョコケーキ発売開始<span class="newicon">NEW</span></dd>
          <dt>2021/08/04</dt>
          <dd>イチゴショート発売開始<span class="newicon">NEW</span></dd>
          <dt>2021/08/05</dt>
          <dd>ガトーショコラ発売開始<span class="newicon">NEW</span></dd>
        </dl>
      </section>
  <!--/#new-->
      <section id="information">
        <h2>information<br><span>店舗情報</span></h2>
        <dl>
          <dt>営業時間</dt>
          <dd>10:00 ~ 18:00</dd>
          <dt>住所</dt>
          <dd>〒380-0803 長野県長野市三輪８丁目２８−３</dd>
          <dt>アクセス</dt>
          <dd>長野電鉄長野線「本郷駅」徒歩５分</dd>
          <dt>電話番号</dt>
          <dd>026-123-4567</dd>
        </dl>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1600.2352335490891!2d138.19940565808926!3d36.663187794994286!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x601d878a4a009e49%3A0x3c122f9e68ded9a!2z5pen5YyX5Zu96KGX6YGT77yI6ZW36YeO5biC77yJ!5e0!3m2!1sja!2sjp!4v1632588188280!5m2!1sja!2sjp" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
      </section>
    </div>
  <!--/#contents-->
  </div>
  <!--/#container-->
  <p class="nav-fix-pos-pagetop"><a href="#">↑</a></p>
  <!--メニュー開閉ボタン-->
  <div id="menubar_hdr" class="close"></div>
  <!--メニューの開閉処理-->
  <script>
    open_close("menubar_hdr", "menubar");
  </script>
  <!--lightbox用jsファイルの読み込み-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.10.0/js/lightbox-plus-jquery.min.js"></script>

</body>

app/views/members/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet" />
  </head>
  <body>
    <strong id="notice2"><%= notice %></strong>
    <div class="video-wrap">
      <%= video_tag("/videos/top.mp4",autoplay: :true, muted: :true, class: 'top-video') %>
       <div class="d-flex justify-content-end">
          <nav class="navbar  navbar-expand-lg navbar-light ml-center gnav-top">
            <ul class="navbar-nav ml-center">
              <% if member_signed_in? %>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to 'My page', members_path(current_member), class: "btn btn-warning" %></p></li>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to 'Items', products_path, class: "btn btn-warning" %></p></li>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to 'Cart', cart_products_path, class: "btn btn-warning" %></p></li>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to "Log out", destroy_member_session_path, method: :delete, class: "btn btn-warning" %></p></li>
              <% elsif admin_signed_in? %>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to '商品一覧', admin_products_path , class: "btn btn-warning" %></p></li>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to '会員一覧', admin_members_path, class: "btn btn-warning" %></p></li>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to '注文履歴一覧', admin_orders_path, class: "btn btn-warning" %></p></li>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to 'ジャンル一覧', admin_genres_path, class: "btn btn-warning" %></p></li>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-warning" %></p></li>
              <% else %>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to 'About', about_path, class: "btn btn-warning" %></p></li>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to 'Items', products_path, class: "btn btn-warning" %></p></li>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to 'Sign up', new_member_registration_path, class: "btn btn-warning" %></p></li>
                <li class="nav-item"><p class="fadein txt01 head-font"><%= link_to 'Log in', member_session_path, class: "btn btn-warning" %></p></li>
              <% end %>
            </ul>
          </nav>
        </div>
        <div class="space">
        </div>
        <div class="container-fuluid">
          <div class="row">
            <div class="col-md-12 flex-row pull-right d-inline">
              <div class="left-space">
                <%= image_tag 'new.jpg',class:'new fadein txt01' %>
                <div class="yoko-top">
                  <% @products.each do |product| %>
                    <%= link_to product_path(product.id) do %>
                      <h4 class="fadein txt01"><strong class="p-name-back"><%= product.name %></strong></h4>
                      <p class="fadein txt01"><%= attachment_image_tag product, :image, fallback: "no_image.jpg", class:"fuwafuwa product-image enn" %></p>
                    <% end %>
                  <% end %>
                  <%= link_to  products_path do %>
                    <%= image_tag 'check.jpg', class:"finger fadein txt01" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </body>